# wrangler.toml (Pages + _worker.js)
name = "ready-to-relate"
pages_build_output_dir = "."
compatibility_date = "2025-09-01"

[vars]
MAIL_FROM = ""                      # leave blank for now (see step 2)
SITE_NAME = "Ready to Relate"
RESEND_API_KEY = "re_your_NEW_key_here"
